name: ZLE
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
permalink: /blog/:year/:month/:day/:title
url: "https://kauntaofficial.github.io"
plugins:
  - jekyll-sitemap
